import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { List, Search } from 'react-bootstrap-icons';
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import pose from "./../images/pose_3.png"

// import axios from '../lib/axios'

const Home = () => {


  const autorisedNotif = () => {

    const randomNotification = () => {
      var randomItem = 5
      var notifTitle = "dhfjfbhf"
      var notifBody = 'Créé par ';
      var notifImg = 'data/img';
      var options = {
        body: notifBody,
        icon: notifImg
      }
      var notif = new Notification(notifTitle, options);
      setTimeout(randomNotification, 30000);
    }

    Notification.requestPermission().then(function (result) {
      if (result === 'granted') {
        randomNotification();
      }
    });
  }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name='application-name' content='PWA App' />
        <meta name='apple-mobile-web-app-capable' content='yes' />
        <meta name='apple-mobile-web-app-status-bar-style' content='default' />
        <meta name='apple-mobile-web-app-title' content='PWA App' />
        <meta name='description' content='Best PWA App in the world' />
        <meta name='format-detection' content='telephone=no' />
        <meta name='mobile-web-app-capable' content='yes' />
        <meta name='msapplication-config' content='/icons/browserconfig.xml' />
        <meta name='msapplication-TileColor' content='#2B5797' />
        <meta name='msapplication-tap-highlight' content='no' />
        <meta name='theme-color' content='#000000' />

        <link rel='apple-touch-icon' href='/icons/touch-icon-iphone.png' />
        <link rel='apple-touch-icon' sizes='152x152' href='/icons/touch-icon-ipad.png' />
        <link rel='apple-touch-icon' sizes='180x180' href='/icons/touch-icon-iphone-retina.png' />
        <link rel='apple-touch-icon' sizes='167x167' href='/icons/touch-icon-ipad-retina.png' />

        <link rel='icon' type='image/png' sizes='32x32' href='/icons/favicon-32x32.png' />
        <link rel='icon' type='image/png' sizes='16x16' href='/icons/favicon-16x16.png' />
        <link rel='manifest' href='/manifest.json' />
        <link rel='mask-icon' href='/icons/safari-pinned-tab.svg' color='#5bbad5' />
        <link rel='shortcut icon' href='/favicon.ico' />
        {/* <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto:300,400,500' /> */}

        <meta name='twitter:card' content='summary' />
        <meta name='twitter:url' content='https://yourdomain.com' />
        <meta name='twitter:title' content='PWA App' />
        <meta name='twitter:description' content='Best PWA App in the world' />
        <meta name='twitter:image' content='https://yourdomain.com/icons/android-chrome-192x192.png' />
        <meta name='twitter:creator' content='@DavidWShadow' />
        <meta property='og:type' content='website' />
        <meta property='og:title' content='PWA App' />
        <meta property='og:description' content='Best PWA App in the world' />
        <meta property='og:site_name' content='PWA App' />
        <meta property='og:url' content='https://yourdomain.com' />
        <meta property='og:image' content='https://yourdomain.com/icons/apple-touch-icon.png' />

        {/* <!-- apple splash screen images -->
<!-- */}
        <link rel='apple-touch-startup-image' href='/images/apple_splash_2048.png' sizes='2048x2732' />
        <link rel='apple-touch-startup-image' href='/images/apple_splash_1668.png' sizes='1668x2224' />
        <link rel='apple-touch-startup-image' href='/images/apple_splash_1536.png' sizes='1536x2048' />
        <link rel='apple-touch-startup-image' href='/images/apple_splash_1125.png' sizes='1125x2436' />
        <link rel='apple-touch-startup-image' href='/images/apple_splash_1242.png' sizes='1242x2208' />
        <link rel='apple-touch-startup-image' href='/images/apple_splash_750.png' sizes='750x1334' />
        <link rel='apple-touch-startup-image' href='/images/apple_splash_640.png' sizes='640x1136' />
        {/* --> */}
      </Head>

      <main className='container p-1 ' >

        <div className='row d-flex flex-column justify-content-center px-4'>
          <h1 className="fs-4">
            Hello <span className='text-blue'>Mike!</span>
          </h1>
          <div className='d-flex'>
            <input className='form-control' type="text" placeholder="recherhez un medecin" />
            <Button variant="outline-primary" >
              <Search color="royalblue" size={25} />
            </Button>

          </div>
          <button className='btn btn-outline-primary mt-3' onClick={autorisedNotif}>
              autoriser les notifications
            </button>
        </div>



        <p className={styles.description}>
          Connectez vous
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>
        <div className='container'>
          <div className='row px-4'>
            <Card className='col-12 card-slider' style={{ background: "#3D35E1", borderRadius: "20px", height: "157px" }} >
              <Card.Img className=' position-absolute ' src={pose.src} style={{ zIndex: '1', width: "202px", height: "202px", bottom: 0 }} />
              <div className='row'>
                <Card.Body className='ps-3 pt-4 mt-3 offset-4 col-8 position-relative text-light' style={{ zIndex: '1' }}>
                  <Card.Title className="text-right">Point covid à 10h50 le 12/09</Card.Title>
                  <Button className="btn bg-light text-dark py-0 rounded-8">Notifier</Button>
                </Card.Body>
              </div>

            </Card>
          </div>
        </div>
{/* 
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Mon planning &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Urgence secours  &rarr;</h2>
            <p>Veuilliez intervennir de toute urgence </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://tismatek.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{'Tismatek'}

        </a>
      </footer>
    </div>
  )
}


export default Home


// export async function getStaticProps() {
//   const response = await axios.post('api/test',[]);
//   console.log(response.data.data)

//   return {
//       props: {
//           offices: response.data.data
//       },
//   }
// }